### ISSUE TITLE
update with the grimoirelab dev env automation script

### ISSUE THREAD

**Issue by vchrombie** [vchrombie/grimoirelab-scripts#1]
Hi @valeriocos

This is in reply to the comment, https://github.com/vchrombie/chaoss-microtasks/issues/10#issuecomment-600724708.

I worked on the changes you have suggested previously and came up with a new script, [glab-dev-env-setup.py](https://github.com/vchrombie/grimoirelab-scripts/blob/master/glab-dev-env-setup.py).

Please go through it when you have time and suggest changes here. I would like to know your views and improve it if necessary.

Finally, when the script is really good shape, I would move it into a gist and update the getting-started section of sirmordred repo with the link to the gist.

This repo has nothing to do with the script. I just created it to store some of my automation scripts. :smile:

**Comment by vchrombie** [comment]
I would add a README later on to the gist. The usage as of now is

* Create a folder 'sources' with all the 15 GrimoireLab components forked, cloned and setting their upstream link using the GitHub API token xxxx:
```
$ python3 glab-dev-setup.py --create --token xxxx --source sources
```

* Update the existing forks present in the 'sources' folder with the latest changes using the GitHub API token xxxx:
```
$ python3 glab-dev-setup.py --update --token xxxx --source sources
```

**Comment by valeriocos** [comment]
Thank you @vchrombie, I'm on it right now (sorry for the delay).

**Comment by valeriocos** [comment]
I have tested and some repos are empty when executing:
```
python3 creator.py -t xxx -c
```

The error thrown is:
```
origin	https://github.com/valeriocos/grimoirelab-cereslib.git (fetch)
origin	https://github.com/valeriocos/grimoirelab-cereslib.git (push)
upstream	https://github.com/chaoss/grimoirelab-cereslib.git (fetch)
upstream	https://github.com/chaoss/grimoirelab-cereslib.git (push)
[2020-04-02 10:49:41,688] - moving into /tmp/sources
[2020-04-02 10:49:42,188] - forking the repository grimoirelab-manuscripts to valeriocos
[2020-04-02 10:49:42,592] - cloning the forked repository grimoirelab-manuscripts
Username for 'https://github.com': valeriocos
Password for 'https://valeriocos@github.com': 
[2020-04-02 10:49:48,604] - folder already exists and is not empty, cloning aborted
[2020-04-02 10:49:48,606] - folder not existing, creating new /tmp/sources/grimoirelab-manuscripts
[2020-04-02 10:49:48,606] - checking remotes
fatal: no es un repositorio git (ni ninguno de los directorios superiores): .git <-- it's not a git repo (nor any of the top directories) 
[2020-04-02 10:49:48,618] - done!
```

I have also noticed that for each repo the script requests to insert username and password

Beyond this, the code looks great, well documented and organized. I have a minor question about the blank line between the docstring and the code of the functions. Which PEP conventions are you following?

**Comment by vchrombie** [comment]
Hi @valeriocos 
Thanks for the reply.

> I have also noticed that for each repo the script requests to insert username and password

Ah, this was not expected. The token should be sufficient. 


> I have tested and some repos are empty when executing:
> 
> ```
> python3 creator.py -t xxx -c
> ```
> 
> The error thrown is:
> 
> ```
> origin	https://github.com/valeriocos/grimoirelab-cereslib.git (fetch)
> origin	https://github.com/valeriocos/grimoirelab-cereslib.git (push)
> upstream	https://github.com/chaoss/grimoirelab-cereslib.git (fetch)
> upstream	https://github.com/chaoss/grimoirelab-cereslib.git (push)
> [2020-04-02 10:49:41,688] - moving into /tmp/sources
> [2020-04-02 10:49:42,188] - forking the repository grimoirelab-manuscripts to valeriocos
> [2020-04-02 10:49:42,592] - cloning the forked repository grimoirelab-manuscripts
> Username for 'https://github.com': valeriocos
> Password for 'https://valeriocos@github.com': 
> [2020-04-02 10:49:48,604] - folder already exists and is not empty, cloning aborted
> [2020-04-02 10:49:48,606] - folder not existing, creating new /tmp/sources/grimoirelab-manuscripts
> [2020-04-02 10:49:48,606] - checking remotes
> fatal: no es un repositorio git (ni ninguno de los directorios superiores): .git <-- it's not a git repo (nor any of the top directories) 
> [2020-04-02 10:49:48,618] - done!
> ```
> 

I think I have figured out the problem. 

The problem is with the repository names. The repository name varies with your forks. You might have forked the repo way back and you might be using them. But the repo names have changed now. 

current repo: https://github.com/chaoss/grimoirelab-manuscripts
your fork: https://github.com/valeriocos/reports

current repo: https://github.com/chaoss/grimoirelab-elk
your fork: https://github.com/valeriocos/GrimoireELK

current repo: https://github.com/chaoss/grimoirelab-cereslib
your fork: https://github.com/valeriocos/grimoirelab-cereslib

If my guess is correct, you must be having sortinghat and cereslib cloned perfectly without any problem as they align with your forks.

The logic was implemented in that way. It takes the repo, forks it to your account (if you have it forked alredy, it will ignore) and clones it with the name in the script. 

Here, it is trying to clone `https://github.com/valeriocos/grimoirelab-manuscripts` but the actual url to your fork is `https://github.com/valeriocos/reports`.

I hope the explanation was clear. Let me know if it is not.

> Beyond this, the code looks great, well documented and organized. 

Thanks!

> I have a minor question about the blank line between the docstring and the code of the functions. Which PEP conventions are you following?

I follow the PEP8 conventions which is already configured in PyCharm. Regarding the spaces, I simply added while coding and forgot to remove them. :sweat_smile:

**Comment by valeriocos** [comment]
Thank you @vchrombie for the detailed reply :)

> Ah, this was not expected. The token should be sufficient.

This happens in combination with having forks with different repo names. I checked that for sortinghat no username/pwd is required.

> I think I have figured out the problem.

Yes! Good catch! :)

> I follow the PEP8 conventions which is already configured in PyCharm. Regarding the spaces, I simply added while coding and forgot to remove them.

Ehehe no worries, the current docstrings are OK, so feel free to decide.

For readability, I would suggest to organize the list here: https://github.com/vchrombie/grimoirelab-scripts/blob/master/glab-dev-env-setup.py#L37 with a repo per line (the decision is up to you).

Please, update the PR in mordred when you have time, thanks! :)

**Comment by vchrombie** [comment]
> https://github.com/vchrombie/grimoirelab-scripts/issues/1#issuecomment-607801552

I have updated the script. :smile:

**Comment by vchrombie** [comment]
Closing this as we got everything right as of now. :smile:
